### ISSUE TITLE
License and/or permission to use

### ISSUE THREAD

**Issue by Famlam** [mpchadwick/tracking-query-params-registry#15]
Hello @mpchadwick,

I'm contacting you on behalf of Osmose ([Website](https://osmose.openstreetmap.fr/) / [Github](https://github.com/osm-fr/osmose-backend)), a Quality Assurance tool for [OpenStreetMap](https://www.openstreetmap.org/). We were [informed](https://github.com/osm-fr/osmose-backend/issues/1950) that the OpenStreetMap database contains some references to URLs with click tracking parameters. We would like to inform the users of Osmose about this, thereby suggesting to remove the click trackers and only leave a clean URL in the database.

For this, we would like to make use of the [tracking query parameters registry csv file](https://github.com/mpchadwick/tracking-query-params-registry/blob/master/_data/params.csv) that you maintain. Although Osmose is non-commercial, the OpenStreetMap database in which the changes would be incorporated by users of Osmose is free to use (ODbL) for everyone, including commercial parties.

We do not know under which license the aforementioned csv file is distributed, and are therefore unsure about its license compatibilty.

Hence, we were hoping that you could state 1) under which license this file is distributed and/or 2) explicitly approve that we can use this file in order to detect links with click trackers, which we can report to users of Osmose in order to improve OpenStreetMap. 

I'm looking forward to your response!

Best regards,
Famlam

**Comment by mpchadwick** [comment]
@Famlam I've updated the repo so that it's licensed via the Unlicense

https://github.com/mpchadwick/tracking-query-params-registry/commit/41b918d8f6589b10bf264ddb4e0d094b875f22f6

Feel free to use it as you'd like. Glad you finding this project useful,
