### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by davidbarratt** [mpchadwick/tracking-query-params-registry#8]
Would you be willing to publish this package to npm?

**Comment by mpchadwick** [comment]
@davidbarratt As this isn't really inherently a JavaScript package I'm not sure it really belongs there. If you wanted to pull this in for consumption via NPM why not just point directly to the GitHub repository? https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub. I use this approach all the time at work to install packages via composer (the PHP package manager).

**Comment by mpchadwick** [comment]
Hey @davidbarratt  I was originally questioning how much sense that this made but I've gone ahead and published it. Given that the project already has a package.json file there's no reason not to put it onto NPM.

https://www.npmjs.com/package/tracking-query-params-registry
